Repository honey-moa/honey-moa-front, pull requests merged in 2024-12, with the labels that each got.

#4 feat/woo(#1): Modal 기능구현
  package-lock.json
  package.json
  src/App.css
  src/App.tsx
  src/components/Modal/index.tsx
  src/components/Modal/style.ts
  src/components/Modal/type.d.ts
  src/index.css
  src/main.tsx
Labels: ✨ Feature

#5 Setting/LJJ : Provider 추가
  package-lock.json
  package.json
  src/provider/AppProvider.tsx
  src/provider/ThemeColorProvider.tsx
  src/provider/type.d.ts
  src/styles/theme/color.ts
  src/styles/theme/index.ts
Labels: ⚙ Setting

#7 Styled/LJJ : 랜딩페이지 퍼블리싱
  public/images/introImage.jpg
  src/App.tsx
  src/components/Layouts/Header/MainHeader.tsx
  src/components/Layouts/Header/RootHeader.tsx
  src/components/Layouts/Header/index.ts
  src/components/Layouts/Header/style.ts
  src/components/Layouts/index.ts
  src/components/Root/Landing/index.tsx
  src/components/Root/Landing/style.ts
  src/components/Root/Landing/type.d.ts
  src/components/Root/Preview/Story.tsx
  src/components/Root/Preview/index.tsx
  src/components/Root/Preview/style.ts
  src/components/Root/index.tsx
  src/provider/ThemeColorProvider.tsx
  src/styles/GlobalStyles.ts
  src/styles/theme/color.ts
Labels: 🎨 Styled

#11 Styled/LJJ: svg추가 및 퍼블리싱
  src/App.tsx
  src/components/Layouts/Header/MainHeader.tsx
  src/components/Layouts/Header/style.ts
  src/components/Main/SideNavigate/index.tsx
  src/components/Main/SideNavigate/style.ts
  src/components/Main/SideNavigate/type.d.ts
  src/components/Main/index.tsx
  src/components/Svg/Svg.tsx
  src/components/Svg/index.ts
  src/components/Svg/type.d.ts
  src/styles/theme/color.ts
  vite.config.ts
Labels: 🎨 Styled

#10 feat/woo(#1): vitest, react-testing-library 설치, modal 테스트 추가
  package-lock.json
  package.json
  src/tests/Modal.test.tsx
  vite.config.ts
Labels: ✅ Test

#12 Styled/LJJ: 꿀통 페이지 퍼블리싱
  src/components/Main/CoupleProfile/index.tsx
  src/components/Main/CoupleProfile/style.ts
  src/components/Main/HoneyList/HoneyCard.tsx
  src/components/Main/HoneyList/index.tsx
  src/components/Main/HoneyList/style.ts
  src/components/Main/HoneyList/type.d.ts
  src/components/Main/SideNavigate/style.ts
  src/components/Main/index.tsx
  src/components/Main/style.ts
  src/components/Svg/Svg.tsx
  src/styles/theme/color.ts
Labels: 🎨 Styled

#13 Styled/LJJ(#8): Auth퍼블리싱 & 이미지컴포넌트 추가
  public/images/siteLogo.jpg
  src/components/Auth/LoginModal.tsx
  src/components/Auth/RegisterModal.tsx
  src/components/Auth/auth.d.ts
  src/components/Auth/index.tsx
  src/components/Auth/style.ts
  src/components/Image/index.tsx
  src/components/Image/style.ts
  src/components/Image/type.d.ts
  src/components/Layouts/Header/RootHeader.tsx
  src/components/Layouts/Header/style.ts
  src/components/Main/SideNavigate/index.tsx
  src/components/Main/SideNavigate/style.ts
  src/components/Modal/index.tsx
  src/components/Root/Landing/style.ts
  src/components/Root/Preview/style.ts
  src/styles/theme/color.ts
Labels: 🎨 Styled, ✨ Feature
