Repository honey-moa/honey-moa-front, pull requests merged in 2025-01, with the labels that each got.

#18 feat/LJJ(#17): Modal -> Funnel로 변경
  package-lock.json
  src/components/Auth/LoginModal.tsx
  src/components/Auth/RegisterModal.tsx
  src/components/Auth/auth.d.ts
  src/components/Auth/index.tsx
  src/components/Auth/type.d.ts
  src/hook/useFunnel.ts
  src/tests/Modal.test.tsx
  src/tests/useFunnel.test.tsx
Labels: ✨ Feature

#19 feat/woo(#14): test provider 설정 변경, workflow 파일 추가:
  .github/workflows/build.yaml
  .github/workflows/test.yaml
  package-lock.json
  package.json
  src/components/Main/HoneyList/index.tsx
  vite.config.ts
Labels: ✅ Test, 🌏 Deploy

#20 auth/LJJ(#8): 로그인 회원가입기능 구현
  package-lock.json
  package.json
  src/apis/auth/endpoint.ts
  src/apis/auth/index.ts
  src/apis/auth/queries.ts
  src/apis/auth/type.d.ts
  src/apis/axiosInstance.ts
  src/components/Auth/LoginModal.tsx
  src/components/Auth/RegisterModal.tsx
  src/components/Auth/type.d.ts
  src/components/Auth/utils.ts
  src/components/Image/index.tsx
  src/components/Image/style.ts
  src/components/Image/type.d.ts
  src/components/Svg/Svg.tsx
  src/hook/useDebounce.ts
  src/provider/AppProvider.tsx
Labels: ✨ Feature, 🔨 Refactor

#22 feat/LJJ(#8): 이메일 인증 모달추가, 에러핸들링
  package-lock.json
  package.json
  src/App.tsx
  src/apis/auth/endpoint.ts
  src/apis/auth/error.ts
  src/apis/auth/queries.ts
  src/apis/auth/type.d.ts
  src/apis/axiosInstance.ts
  src/components/Auth/ChangePassword.tsx
  src/components/Auth/LoginModal.tsx
  src/components/Auth/RegisterModal.tsx
  src/components/Auth/SendEmailForChnagePasswordModal.tsx
  src/components/Auth/VerificationEmailModal.tsx
  src/components/Auth/changePwStyle.ts
  src/components/Auth/index.tsx
  src/components/Auth/style.ts
  src/components/Auth/type.d.ts
  src/components/Layouts/Header/SettingHeader.tsx
  src/components/Layouts/Header/index.ts
  src/components/Layouts/Header/style.ts
  src/components/Layouts/Header/type.d.ts
  src/components/Loading/Spinner.tsx
  src/components/Loading/index.ts
  src/components/Loading/style.ts
  src/components/Svg/Svg.tsx
  src/components/index.ts
  src/store/authStore/index.ts
  src/store/authStore/type.d.ts
  src/store/authStore/userInfoStore.ts
  src/styles/theme/color.ts
  tsconfig.app.json
  vite.config.ts
Labels: 🎨 Styled, ✨ Feature

#27 Feat/util UI: 쓸모있는 UI 만들기
  package-lock.json
  package.json
  src/apis/auth/queries.ts
  src/components/Auth/ChangePassword.tsx
  src/components/Auth/LoginModal.tsx
  src/components/Auth/RegisterModal.tsx
  src/components/Auth/SendEmailForChnagePasswordModal.tsx
  src/components/Auth/index.tsx
  src/components/Auth/style.ts
  src/components/PopUp/Toast.tsx
  src/components/PopUp/Tooltip.tsx
  src/components/PopUp/index.ts
  src/components/PopUp/style.ts
  src/components/PopUp/type.d.ts
  src/components/index.ts
  src/provider/AppProvider.tsx
  src/provider/TestProvider.tsx
  src/store/toastStore/type.d.ts
  src/store/toastStore/useToastStore.ts
  src/tests/Auth.test.tsx
Labels: 🎨 Styled, ✨ Feature

#24 feat/woo(#3): 연결 모달 박스 구현
  src/App.tsx
  src/components/Connection/index.tsx
  src/components/Connection/style.ts
  src/components/Connection/type.d.ts
  src/components/Svg/Svg.tsx
Labels: ✨ Feature

#29 연결 안됐을 때, 메인 페이지 퍼블리싱
  src/App.tsx
  src/components/Layouts/Header/UnconnectedHeader.tsx
  src/components/Layouts/Header/index.ts
  src/components/Layouts/Header/style.ts
  src/components/Main/Contents/HoneyCard.tsx
  src/components/Main/Contents/HoneyList.tsx
  src/components/Main/Contents/UnConnectedList.tsx
  src/components/Main/Contents/index.ts
  src/components/Main/Contents/style.ts
  src/components/Main/Contents/type.d.ts
  src/components/Main/Main.tsx
  src/components/Main/Profile/Couple.tsx
  src/components/Main/Profile/UnConnected.tsx
  src/components/Main/Profile/index.ts
  src/components/Main/Profile/style.ts
  src/components/Main/SideNavigate/style.ts
  src/components/Main/index.ts
  src/components/Main/index.tsx
  src/components/Svg/Svg.tsx
  src/styles/theme/color.ts
Labels: 🎨 Styled, 🔨 Refactor

#31 블로그 글 쓰기 퍼블리싱 및 기능 구현
  package-lock.json
  package.json
  src/App.tsx
  src/components/Auth/ChangePassword.tsx
  src/components/Auth/LoginModal.tsx
  src/components/Auth/RegisterModal.tsx
  src/components/Auth/SendEmailForChnagePasswordModal.tsx
  src/components/Auth/utils.ts
  src/components/Layouts/Header/index.ts
  src/components/Main/Contents/HoneyCard.tsx
  src/components/Main/Contents/HoneyList.tsx
  src/components/Main/Contents/index.ts
  src/components/Main/Contents/style.ts
  src/components/Main/Contents/type.d.ts
  src/components/Main/Honey/BlogComments.tsx
  src/components/Main/Honey/BlogContents.tsx
  src/components/Main/Honey/Honey.tsx
  src/components/Main/Honey/index.ts
  src/components/Main/Honey/style.ts
  src/components/Main/Honey/type.d.ts
  src/components/Main/Main.tsx
  src/components/Main/SideNavigate/index.tsx
  src/components/Main/SideNavigate/style.ts
  src/components/PopUp/Tooltip.tsx
  src/components/Post/Editor.tsx
  src/components/Post/Post.tsx
  src/components/Post/PostHeader.tsx
  src/components/Post/Tags.tsx
  src/components/Post/index.ts
  src/components/Post/style.ts
  src/components/Post/type.d.ts
  src/components/Post/utils.ts
  src/components/Svg/Svg.tsx
  src/components/common/ScrollToTop.tsx
  src/provider/AppProvider.tsx
  src/styles/GlobalStyles.ts
  src/utils/changeInfo/index.ts
  src/utils/changeInfo/text.ts
  src/utils/changeInfo/toggle.ts
  src/utils/index.ts
Labels: 🎨 Styled, ✨ Feature

#33 refactor/LJJ(#32): auth에러 핸들링
  package-lock.json
  package.json
  src/App.tsx
  src/apis/auth/error.ts
  src/apis/auth/type.d.ts
  src/apis/axiosInstance.ts
  src/apis/interceptors.ts
  src/components/Auth/ChangePassword.tsx
  src/components/Auth/LoginModal.tsx
  src/components/Auth/RegisterModal.tsx
  src/components/Auth/SendEmailForChnagePasswordModal.tsx
  src/components/Error/ErrorBoundary.tsx
  src/components/Error/Fallback.tsx
  src/components/Error/NotFound.tsx
  src/components/Error/index.ts
  src/components/Error/style.ts
  src/components/PopUp/Toast.tsx
  src/components/PopUp/index.ts
  src/components/PopUp/style.ts
  src/components/PopUp/type.d.ts
  src/components/index.ts
  src/provider/AppProvider.tsx
  src/store/toastStore/type.d.ts
  src/store/toastStore/useToastStore.ts
Labels: 🔨 Refactor

#35 feat/woo(#3): 연결 api 도입
  src/App.tsx
  src/apis/auth/endpoint.ts
  src/apis/axiosInstance.ts
  src/apis/connection/endpoint.ts
  src/apis/connection/error.ts
  src/apis/connection/index.ts
  src/apis/connection/queries.ts
  src/apis/connection/type.d.ts
  src/apis/interceptors.ts
  src/components/Connection/UserInfo/index.tsx
  src/components/Connection/UserInfo/style.ts
  src/components/Connection/index.tsx
  src/components/Connection/style.ts
  src/components/Connection/type.d.ts
  src/components/Main/Main.tsx
  src/components/Main/Profile/UnConnected.tsx
  src/components/Svg/Svg.tsx
Labels: 📬 API, ✨ Feature

#45 테마 설정
  src/components/Setting/Modals/ChangeThemeModal.tsx
  src/components/Setting/Modals/style.ts
  src/components/Setting/Setting.tsx
  src/hook/useLocalStorage.ts
  src/provider/ThemeColorProvider.tsx
  src/styles/GlobalStyles.ts
  src/styles/theme/color.ts
Labels: 🎨 Styled, ✨ Feature

#50 비회원 접근시 모달 띄우기
  src/App.tsx
  src/apis/auth/queries.ts
  src/components/Auth/AuthFunnelModal.tsx
  src/components/Auth/SendEmailForChangePasswordModal.tsx
  src/components/Auth/index.tsx
  src/components/Auth/type.d.ts
  src/components/Modal/index.tsx
  src/components/Modal/style.ts
  src/components/Modal/type.d.ts
  src/components/Root/Landing/index.tsx
  src/components/Root/Landing/style.ts
  src/components/Setting/Setting.tsx
  src/hook/useLocalStorage.ts
  src/provider/AppProvider.tsx
  src/provider/type.d.ts
  src/routes/AccessAuth.tsx
  src/routes/ValidationRoute.tsx
  src/routes/type.d.ts
  src/store/authStore/type.d.ts
  src/tests/Auth.test.tsx
Labels: 🎨 Styled, ✨ Feature

#48 프로필 퍼블리싱 및 리팩터링
  src/components/Image/index.tsx
  src/components/Setting/Modals/EditCoupleProfileModal.tsx
  src/components/Setting/Modals/EditMyProfileModal.tsx
  src/components/Setting/Modals/EditProfileImageOverlayComponent.tsx
  src/components/Setting/Modals/style.ts
  src/components/Setting/Modals/type.d.ts
  src/components/Svg/Svg.tsx
  src/utils/changeInfo/image.ts
  src/utils/changeInfo/index.ts
Labels: 🎨 Styled, ✨ Feature, 🔨 Refactor
