Repository honey-moa/honey-moa-front, pull requests merged in 2025-02, with the labels that each got.

#56 feat/woo(#51): 채팅 박스 퍼블리싱
  src/apis/axiosInstance.ts
  src/apis/connection/endpoint.ts
  src/components/Chat/ChatBox/index.tsx
  src/components/Chat/ChatBox/style.ts
  src/components/Chat/ChatButton/index.tsx
  src/components/Chat/ChatButton/style.ts
  src/components/Chat/ChatPage/index.tsx
  src/components/Chat/ChatPage/style.ts
  src/components/Chat/index.ts
  src/components/Chat/type.d.ts
  src/components/Main/Main.tsx
  src/components/Svg/Svg.tsx
  src/provider/AppProvider.tsx
  src/routes/ValidationRoute.tsx
Labels: 🎨 Styled, ✨ Feature

#61 refactor/LJJ(#57): theme 타입 추론
  package-lock.json
  package.json
  src/components/PopUp/style.ts
  src/styles/theme/color.ts
  src/styles/theme/type.d.ts
Labels: 🔨 Refactor

#59 feat/woo(#3): 연결 상태 조회 api 추가
  src/apis/auth/error.ts
  src/apis/auth/type.d.ts
  src/apis/connection/error.ts
  src/apis/connection/type.d.ts
  src/apis/type.d.ts
  src/apis/user/endpoint.ts
  src/apis/user/error.ts
  src/apis/user/index.ts
  src/apis/user/type.d.ts
  src/components/Chat/ChatBox/index.tsx
  src/components/Chat/ChatBox/style.ts
  src/components/Chat/ChatButton/index.tsx
  src/components/Chat/ChatButton/style.ts
  src/components/Chat/index.ts
  src/components/Chat/type.d.ts
  src/components/Main/Main.tsx
  src/provider/AppProvider.tsx
  src/store/connectionStore/connectionInfoStore.ts
  src/store/connectionStore/type.d.ts
Labels: 📬 API, ✨ Feature

#65 블로그 생성 로직 추가
  src/apis/auth/queries.ts
  src/apis/axiosInstance.ts
  src/apis/blog/endpoint.ts
  src/apis/blog/error.ts
  src/apis/blog/index.ts
  src/apis/blog/queries.ts
  src/apis/blog/type.d.ts
  src/apis/interceptors.ts
  src/apis/user/queries.ts
  src/components/Main/CreateBlogModal/index.tsx
  src/components/Main/CreateBlogModal/style.ts
  src/components/Main/CreateBlogModal/type.d.ts
  src/components/Main/Main.tsx
  src/components/Main/style.ts
  src/components/index.ts
Labels: ✨ Feature

#67 커플쪽 블로그 퍼블리싱
  src/apis/blog/error.ts
  src/apis/blog/queries.ts
  src/apis/blog/type.d.ts
  src/apis/user/type.d.ts
  src/components/Blog/Blog.tsx
  src/components/Blog/style.ts
  src/components/Chat/ChatBox/index.tsx
  src/components/Layouts/Header/BlogHeader.tsx
  src/components/Layouts/Header/index.ts
  src/components/Layouts/Header/style.ts
  src/components/Layouts/Header/type.d.ts
  src/components/Layouts/Profile/Couple.tsx
  src/components/Layouts/Profile/TogetherImage.tsx
  src/components/Layouts/Profile/UnConnected.tsx
  src/components/Layouts/Profile/index.ts
  src/components/Layouts/Profile/style.ts
  src/components/Layouts/Profile/type.d.ts
  src/components/Layouts/SideNavigate/AbleBlogSide.tsx
  src/components/Layouts/SideNavigate/UnConnectedSide.tsx
  src/components/Layouts/SideNavigate/index.ts
  src/components/Layouts/SideNavigate/style.ts
  src/components/Layouts/SideNavigate/type.d.ts
  src/components/Layouts/index.ts
  src/components/Main/Contents/UnConnectedList.tsx
  src/components/Main/Main.tsx
  src/components/Main/Profile/Couple.tsx
  src/components/Main/index.ts
  src/store/connectionStore/connectionInfoStore.ts
  src/store/connectionStore/type.d.ts
Labels: 🎨 Styled, ✨ Feature

#69 블로그 게시글 생성 api 연결
  src/apis/blog/endpoint.ts
  src/apis/blog/error.ts
  src/apis/blog/queries.ts
  src/apis/blog/type.d.ts
  src/components/Blog/Post/CreateBlogPostModal.tsx
  src/components/Blog/Post/Editor.tsx
  src/components/Blog/Post/Post.tsx
  src/components/Blog/Post/PostHeader.tsx
  src/components/Blog/Post/SuccessNewBlogPostToast.tsx
  src/components/Blog/Post/Tags.tsx
  src/components/Blog/Post/index.ts
  src/components/Blog/Post/style.ts
  src/components/Blog/Post/type.d.ts
  src/components/Layouts/Header/index.ts
  src/components/Layouts/SideNavigate/AbleBlogSide.tsx
  src/components/Layouts/SideNavigate/style.ts
  src/components/Main/CreateBlogModal/index.tsx
  src/components/Main/CreateBlogModal/style.ts
  src/components/Main/CreateBlogModal/type.d.ts
  src/components/PopUp/style.ts
  src/components/Post/Editor.tsx
  src/components/Post/style.ts
  src/components/Post/utils.ts
  src/components/Svg/Svg.tsx
  src/routes/ValidationRoute.tsx
  src/styles/theme/color.ts
Labels: 🎨 Styled, ✨ Feature

#75 블로그 게시글 조회
  src/apis/blog/endpoint.ts
  src/apis/blog/error.ts
  src/apis/blog/queries.ts
  src/apis/blog/type.d.ts
  src/components/Blog/Blog.tsx
  src/components/Blog/Honey/BlogComments.tsx
  src/components/Blog/Honey/BlogContents.tsx
  src/components/Blog/Honey/Honey.tsx
  src/components/Blog/Honey/LeftSideNav.tsx
  src/components/Blog/Honey/RightSideNav.tsx
  src/components/Blog/Honey/index.ts
  src/components/Blog/Honey/style.ts
  src/components/Blog/Honey/type.d.ts
  src/components/Layouts/Profile/Couple.tsx
  src/components/Layouts/Profile/TogetherImage.tsx
  src/components/Layouts/Profile/style.ts
  src/components/Layouts/Profile/type.d.ts
  src/components/Main/Contents/index.ts
  src/components/Main/Honey/BlogContents.tsx
  src/components/Main/Honey/Honey.tsx
  src/components/Main/Honey/type.d.ts
  src/components/Svg/Svg.tsx
  src/routes/ValidationRoute.tsx
Labels: 🎨 Styled, 📬 API, ✨ Feature

#78 test환경 http적용
  DockerFile
  index.html
  nginx/default.conf
  vite.config.ts
Labels: ✅ Test, 🌏 Deploy

#88 deploy/LJJ(#77): 잔디가즈아
  .github/workflows/cicdDocker.yaml
Labels: 🌏 Deploy

#89 찐 최종 deploy
  nginx/default.conf
Labels: 💻 CrossBrowsing

#91 deploy/LJJ(#77): 진짜 찐막 최종
  Dockerfile
  nginx/client-default.conf
  nginx/default.conf
Labels: 🌏 Deploy

#92 deploy/LJJ(#77): env추가
  .github/workflows/cicdDocker.yaml
  Dockerfile
Labels: 🌏 Deploy

#94 ci/cd 수정
  .github/workflows/cicdDocker.yaml
Labels: 🌏 Deploy

#96 feat/LJJ(#95): 블로그 페이지 네이션 구현
  src/apis/blog/endpoint.ts
  src/apis/blog/error.ts
  src/apis/blog/queries.ts
  src/apis/blog/type.d.ts
  src/assets/react.svg
  src/components/Blog/Blog.tsx
  src/components/Blog/BlogList/BlogListEachHoneyCard.tsx
  src/components/Blog/BlogList/PrivateBlogList.tsx
  src/components/Blog/BlogList/PublicBlogList.tsx
  src/components/Blog/BlogList/style.ts
  src/components/Blog/BlogList/type.d.ts
  src/components/Blog/style.ts
  src/components/Layouts/Profile/style.ts
  src/components/Layouts/SideNavigate/style.ts
  src/components/Main/Main.tsx
  src/components/Main/index.ts
  src/components/Svg/Svg.tsx
  src/routes/ValidationRoute.tsx
  src/styles/GlobalStyles.ts
  src/utils/date/formatDate.ts
  src/utils/date/getNowDate.ts
  src/utils/date/index.ts
  src/utils/index.ts
Labels: 🎨 Styled, ✨ Feature

#98 블로그 이미지 선 업로드 구현
  src/apis/attachment/endpoint.ts
  src/apis/attachment/error.ts
  src/apis/attachment/index.ts
  src/apis/attachment/queries.ts
  src/apis/attachment/type.d.ts
  src/apis/type.d.ts
  src/components/Blog/Post/CreateBlogPostModal.tsx
  src/components/Blog/Post/Editor.tsx
  src/components/Blog/Post/SuccessNewBlogPostToast.tsx
  src/components/Blog/Post/style.ts
Labels: 🎨 Styled, ✨ Feature

#100 블로그 포스트 관련 PR
  src/apis/blog/queries.ts
  src/apis/blog/type.d.ts
  src/components/Auth/LoginModal.tsx
  src/components/Auth/VerificationEmailModal.tsx
  src/components/Blog/Blog.tsx
  src/components/Blog/BlogList/BlogListEachHoneyCard.tsx
  src/components/Blog/BlogList/PrivateBlogList.tsx
  src/components/Blog/BlogList/style.ts
  src/components/Blog/BlogList/type.d.ts
  src/components/Blog/Honey/LeftSideNav.tsx
  src/components/Blog/Post/CreateBlogPostModal.tsx
  src/components/Blog/Post/EditBlogPost.tsx
  src/components/Blog/Post/Editor.tsx
  src/components/Blog/Post/PostHeader.tsx
  src/components/Blog/Post/SuccessNewBlogPostToast.tsx
  src/components/Blog/Post/Tags.tsx
  src/components/Blog/Post/style.ts
  src/components/Blog/Post/type.d.ts
  src/components/Layouts/SideNavigate/AbleBlogSide.tsx
  src/components/Layouts/SideNavigate/style.ts
  src/components/Main/CreateBlogModal/index.tsx
  src/components/Main/Main.tsx
  src/components/Root/Landing/index.tsx
  src/routes/ValidationRoute.tsx
Labels: ✨ Feature

#76 accessToken 재발급
  src/apis/auth/endpoint.ts
  src/apis/auth/queries.ts
  src/apis/auth/type.d.ts
  src/apis/interceptors.ts
  src/components/Main/Main.tsx
  src/components/Root/Landing/index.tsx
Labels: 📬 API, ✨ Feature

#102 접근권한 및 모달 수정
  package-lock.json
  package.json
  src/apis/auth/endpoint.ts
  src/apis/blog/queries.ts
  src/apis/interceptors.ts
  src/components/Auth/AuthFunnelModal.tsx
  src/components/Auth/index.tsx
  src/components/Auth/type.d.ts
  src/components/Blog/Post/PostHeader.tsx
  src/components/Connection/Connection.tsx
  src/components/Connection/Modal/ConnectionModal.tsx
  src/components/Connection/Modal/ManageModal.tsx
  src/components/Connection/type.d.ts
  src/components/Layouts/Header/UnconnectedHeader.tsx
  src/components/Main/Main.tsx
  src/components/Modal/index.tsx
  src/components/Modal/type.d.ts
  src/components/Setting/Setting.tsx
  src/routes/AccessAuth.tsx
  src/tests/Modal.test.tsx
  tsconfig.app.json
  tsconfig.json
  vite.config.ts
  vitest-setup.ts
Labels: 🔨 Refactor

#104 설정 로직 추가
  src/apis/blog/endpoint.ts
  src/apis/blog/error.ts
  src/apis/blog/queries.ts
  src/apis/blog/type.d.ts
  src/apis/connection/endpoint.ts
  src/apis/connection/error.ts
  src/apis/connection/queries.ts
  src/apis/interceptors.ts
  src/apis/user/endpoint.ts
  src/apis/user/error.ts
  src/apis/user/queries.ts
  src/apis/user/type.d.ts
  src/components/Auth/VerificationEmailModal.tsx
  src/components/Auth/index.tsx
  src/components/Blog/BlogList/PrivateBlogList.tsx
  src/components/Setting/Modals/EditCoupleProfileModal.tsx
  src/components/Setting/Modals/EditMyProfileModal.tsx
  src/components/Setting/Modals/EmailValidationModal.tsx
  src/components/Setting/Modals/style.ts
  src/components/Setting/Modals/type.d.ts
  src/components/Setting/Setting.tsx
Labels: ✨ Feature
